namespace :api do
  desc 'API Routes'
  task :routes => :environment do
    API::Root.routes.each_with_index do |api, index|
      number = (index + 1).to_s.ljust(4)
      method = api.route_method.ljust(10)
      # added **rescue next** to skip methods generated by gem grape-swagger
      path = api.route_path.gsub(':version', api.route_version) rescue api.route_path
      puts "  #{number}  #{method} #{path}"
    end
  end
end